# Sea-ORM 架构功能测试（绕过 CLI）

name = "customer-service-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core framework
axum = { version = "0.7", features = ["ws", "tokio", "headers"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Sea-ORM 核心（移除 CLI）
sea-orm = { version = "0.12", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros", "debug-print"] }
# migration = { path = "./migration" }  # 暂时禁用迁移

# 认证与安全
jsonwebtoken = "8"
bcrypt = "0.14"

# HTTP 客户端与服务器
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "fs", "trace"] }
hyper = "1.0"
mime = "0.3"
mime_guess = "2.0"

# 数据库
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-rustls", "chrono"] }

# 工具
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
tokio-test = "0.4"

[[bin]]
name = "server"
path = "src/main.rs"