[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

# Linux musl 目标 (静态链接，无需系统库) - 推荐用于部署
[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

# Linux GNU 目标 (动态链接)
[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

# 环境变量
[env]
PKG_CONFIG_ALLOW_CROSS = "1"
SQLX_OFFLINE = "true"

# 发布版本优化
[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true